### ISSUE TITLE
'unexpected token import'

### ISSUE THREAD

**Issue by p-i-** [lcdsantos/menuspy#5]
I think it needs transpiling, right?

Could you possibly add this to the README.md?  Looks like even the latest Version of Chrome doesn't support `import`:

![screen shot 2017-09-06 at 17 31 15](https://user-images.githubusercontent.com/693495/30131936-80d7d604-9346-11e7-8593-fb9ded173a8d.png)

**Comment by lcdsantos** [comment]
You should be using the script from the `dist` folder. It's transpiled and bundled already.
