### ISSUE TITLE
header > nav > ul > li > a structure in mandatory?

### ISSUE THREAD

**Issue by hackuun** [lcdsantos/menuspy#6]
Hello. I had this markup and plugin worked incorrect `nav > a`

After I add markup from example it begin to work. 

Is this structure is mandatory?

**Comment by lcdsantos** [comment]
The active class will be applied to the closest parent element of `a`.

In the case of `nav > a`, the class will be applied to `nav`, which is not useful.

**Comment by hackuun** [comment]
@lcdsantos It make sense. Thanks!
