### ISSUE TITLE
Provide a destroy method

### ISSUE THREAD

**Issue by hackuun** [lcdsantos/menuspy#7]
I have a SPA and I don't want Menuspy on other pages beside where I exactly put it. 
Right now, even if I navigate from the page where I required menuspy, it still exist.
Please provide a method to destroy menuspy.

**Comment by lcdsantos** [comment]
Added in v.1.2.0.

Usage:
```js
var elm = document.querySelector('#main-header');
var ms = new MenuSpy(elm);

ms.destroy();
```

**Comment by ogous** [comment]
@lcdsantos what about a refresh, update method?
